### ISSUE TITLE
Append more information for error

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#123] opened 2017-02-03 10:14 UTC
We need to add object as data for error for more detailed information here https://github.com/Travelport-Ukraine/uapi-json/blame/b174634f9dcbb7149be375111218a1cd6e3cb9d4/src/Services/Air/AirParser.js#L92

**Comment by articice** [comment] 2017-09-01 04:29
This particular line has been fixed by @shmuga in duplicate issue #129 in this commit 6e223081d85d41451ebb28be454026b32eab1b4e

The error object is passed the way it is, without any parsing, which is typical for most errors in uapi-json.

Unfortunately, there's no sample XML for the "VALID FORM OF ID FOID REQUIRED" error mentioned in the code to come up with some error object parsing.
@shmuga @dchertousov maybe you have it?

Closing this issue as a duplicate of #129

**Closed by articice** 2017-09-01 04:29 UTC
Labels: enhancement
