### ISSUE TITLE
Support for <common:OverridePCC /> tag

### ISSUE THREAD

**Issue by MiseCZ** [Travelport-Ukraine/uapi-json#50] opened 2016-10-27 10:36 UTC
We would like to have support for common:OverridePCC tag in AirPriceReq request and possibly in all of AirService requests. I'm not sure about other services.

In our current solution we are  using:
`<com:OverridePCC ProviderCode="{$providerCode}" PseudoCityCode="{$pcc}"/>`

I think:
- The `Settings` object could be probably extended with OverridePCCCode attribute. ProviderCode is probably always 1G. If not OverridePCC should be object.
- The templates from /src/Services/Air/templates should support this setting.

What do you think about it? Thanks.

**Comment by shmuga** [comment] 2016-10-27 11:03
Looks good for me.

I think you should extend settings object as you mentioned.
We always use provider 1G in our products. So I think we can just add property OverridePCC with value what PCC should we use. After that you should update all xml templates with something like (we are using [handlebars.js](http://handlebarsjs.com/) as template engine)

```xml
{{#if OverridePCC}}
<com:OverridePCC ProviderCode="1G" PseudoCityCode="{{OverridePCC}}"/>
{{/if}}
```

After that you should extend globals in all templates like in this line.

https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Request/uapi-request.js#L64

**Comment by MiseCZ** [comment] 2016-10-27 13:03
Thanks for reply. I think @jirismika will deliver this function next week.

**Comment by shmuga** [comment] 2016-10-31 22:40
@dchertousov Has landed last update with `TerminalService` 🎆 .
He added `emulatePcc` property to costructor of this service.
Maybe we can use it in other services as param for pcc overriding?
@Smotrov @MiseCZ  @dchertousov what do you think? Whould it be comfortable creating whole service with overrided pcc or passing it to the function when needed?

**Comment by dchertousov** [comment] 2016-10-31 22:43
@shmuga looks good for me

**Comment by jirismika** [comment] 2016-11-09 11:55
Setting `emulatePcc` property using constructor is just fine and I believe we can use it on other services too. 
The question is, which services are supporting it, to know which templates we can start updating. I remember only the UniversalRecordRetrieve and AirPrice supports this, but I believe that it's not the end of the list ...

**Comment by shmuga** [comment] 2016-11-14 23:50
@jirismika Sorry for so long response. I just missed this one.
As I wrote before you can just put it as an option to the constructor and add to global scope in templates.
We can deprecate old usage for new clear inteface. @dchertousov what do you think?

**Comment by dchertousov** [comment] 2016-11-17 11:42
@MiseCZ , @jirismika I think we will need this shortly.
If I'll include this to the nearest milestone 0.5.3 will you have time to provide such changes?

**Comment by shmuga** [comment] 2016-11-17 15:30
@dchertousov I think we should probably start versioning in 0.6.0.
Let's land new versions in the higher number. And minor fixes/changes in last semver number (like # 0.5.**3**)

**Comment by jirismika** [comment] 2016-11-22 14:52
Hello, I'm sorry for a late reply. 
I'm now on it, but I am a bit struggling as I am not sure how to test the results of the requests and I am not much familiar with the requests in the templates directory, so any tips how to check/test the requests are welcomed.
Anyway, I've prepared a very small commit, to see if I understand it correctly, please check the code there https://github.com/Travelport-Czech/uapi-json/commit/dfb041c393e00a9a7947acc2c3a2c1eebda17f72 and let me know if I am doing it how it was intended.

**Comment by shmuga** [comment] 2016-11-28 01:21
@jirismika Hello there!
You've made a good start but here is some improvements  https://github.com/Travelport-Czech/uapi-json/commit/dfb041c393e00a9a7947acc2c3a2c1eebda17f72

> so any tips how to check/test the requests are welcomed.
There is such problem that we have no tests for our requests for now.
But I hope everything will work well if you just add needed param.

**Comment by jirismika** [comment] 2016-11-29 15:43
Hello @shmuga Thanks for comments.
But it still depends on the way how to inject the parameter to service. It's actually the reason why I've commited such a small part of code and asked if I am doing it correctly, because I wasn't feeling right about refactoring all the methods. It really isn't very nice to add another parameter and be forced to refactor all the methods, but if we are already using that parameter in TerminalService, it should be used the same way everywhere.

So, do you want me to revert it back and use the `auth` or should I continue in refactoring of the other methods?

**Comment by shmuga** [comment] 2016-11-30 10:10
@jirismika I want to have a comment of @dchertousov. After that we'll decide

**Comment by dchertousov** [comment] 2016-11-30 11:06
You guys proposed a better way by putting overridePcc into auth.
I will update Terminal service according to your changes right after you finish.

**Comment by jirismika** [comment] 2016-11-30 12:59
Thank you for clarification! So I've [started again](https://github.com/Travelport-Czech/uapi-json/commit/712062ca39ad39d7f8b65ce85089b95a90cc9698) and I'll add more requests step by step.

**Comment by shmuga** [comment] 2016-11-30 13:00
Awesome!

**Comment by dchertousov** [comment] 2017-01-12 10:50
@MiseCZ , @jirismika is there any update on that according to the conversation in #81?
Could you reference me to the branch where I could find that latest changes?

**Comment by dchertousov** [comment] 2017-01-12 13:22
Decided to replace `overridePcc` attribute with `emulatePcc`

**Comment by dchertousov** [comment] 2017-01-12 13:40
Closing this issue as #89 is merged with the latest changes.

**Closed by dchertousov** 2017-01-12 13:40 UTC
Labels: enhancement
